//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.DarussalamMobile
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DarussalamMobileCart
    {
        public int Id { get; set; }
        public string OrderId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> BookId { get; set; }
        public string BookName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> UnitTotal { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<bool> SubmitStatus { get; set; }
        public Nullable<bool> ProcessStatus { get; set; }
    
        public virtual tbl_DarusSalamBook tbl_DarusSalamBook { get; set; }
        public virtual tbl_DarussalamMobileUser tbl_DarussalamMobileUser { get; set; }
    }
}
